//
// E:\github\ISPC-DirectX-Graphics-Samples\Samples\Desktop\D3D12nBodyGravity\src\nBodyGravity_ispc_sse4.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_E__GITHUB_ISPC_DIRECTX_GRAPHICS_SAMPLES_SAMPLES_DESKTOP_D3D12NBODYGRAVITY_SRC_NBODYGRAVITY_ISPC_SSE4_H
#define ISPC_E__GITHUB_ISPC_DIRECTX_GRAPHICS_SAMPLES_SAMPLES_DESKTOP_D3D12NBODYGRAVITY_SRC_NBODYGRAVITY_ISPC_SSE4_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT_Vec4__
#define __ISPC_STRUCT_Vec4__
struct Vec4 {
    float x;
    float y;
    float z;
    float w;
};
#endif

#ifndef __ISPC_STRUCT_Particle__
#define __ISPC_STRUCT_Particle__
struct Particle {
    struct Vec4 position;
    struct Vec4 velocity;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void ProcessParticles(uint32_t particleStart, uint32_t particleCount, struct Particle * readParticles, struct Particle * writeParticles, uint32_t totalParticles);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_E__GITHUB_ISPC_DIRECTX_GRAPHICS_SAMPLES_SAMPLES_DESKTOP_D3D12NBODYGRAVITY_SRC_NBODYGRAVITY_ISPC_SSE4_H
